Dental_Clinic_System/Dental_Clinic_System/Areas/Admin/Controllers/ManagerClinicController.cs
using Dental_Clinic_System.Areas.Admin.ViewModels;
using Dental_Clinic_System.Helper;
using Dental_Clinic_System.Models.Data;
using Dental_Clinic_System.Services.EmailSender;
using Dental_Clinic_System.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Dental_Clinic_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "GetAppointmentStatus", Roles = "Admin, Mini Admin")]
    public class ManagerClinicController : Controller
    {
        private readonly DentalClinicDbContext _context;
        private readonly IEmailSenderCustom _emailSender;

        public ManagerClinicController(DentalClinicDbContext context, IEmailSenderCustom emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }

        #region Show List Clinic
        //===================LIST CLINIC===================
        //[Route("ListClinic")]
        public async Task<IActionResult> ListClinic()
        {
            //Lấy dữ liệu từ cơ sở dữ liệu
            var clinics = await (from clinic in _context.Clinics
                                 join account in _context.Accounts
                                 on clinic.ManagerID equals account.ID

								 where account.Role == "Quản Lý" && clinic.ClinicStatus == "Hoạt Động"
								 select new ManagerClinicVM
								 {
									 ClinicName = clinic.Name,
									 ProvinceName = clinic.ProvinceName,
									 Image = clinic.Image,
									 Id = clinic.ID,
									 ManagerName = account.LastName + " " + account.FirstName
								 }).ToListAsync();

            return View(clinics);
        }
        #endregion

        #region Tìm kiếm phòng khám (Search)
        //===================TÌM KIẾM===================
        //[Route("SearchClinic")]
        public async Task<IActionResult> SearchClinic(string search)
        {
            //Nếu search rỗng, sẽ chuyển hướng đến ListClinic
            if (string.IsNullOrEmpty(search))
            {
                return RedirectToAction(nameof(ListClinic));
            }

            var query = from clinic in _context.Clinics
                        join account in _context.Accounts
                        on clinic.ManagerID equals account.ID
                        where account.Role == "Quản Lý" && clinic.ClinicStatus == "Hoạt Động"
                        select new ManagerClinicVM
                        {
                            ClinicName = clinic.Name,
                            //Address = clinic.Address,
                            Province = clinic.Province,
                            Image = clinic.Image,
                            ManagerName = account.LastName + " " + account.FirstName
                        };

            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(c => c.ClinicName.Contains(search));
            }

            var clinics = await query.ToListAsync();

            var clinicList = clinics.Select(c => new ManagerClinicVM
            {
                ClinicName = c.ClinicName,
                //Address = c.Address,
                Province = c.Province,
                Image = c.Image,
                ManagerName = c.ManagerName
            }).ToList();

            return View(nameof(ListClinic), clinics);
        }
        #endregion

        #region Thêm phòng khám (ADD)
        //===================THÊM PHÒNG KHÁM===================
        [HttpGet]
        public async Task<IActionResult> CreateClinic()
        {
            var unassignedManagers = await _context.Accounts
            .Where(a => a.Role == "Quản Lý" && !_context.Clinics.Any(c => c.ManagerID == a.ID) && a.AccountStatus == "Hoạt Động")
            .Select(a => new
            {
                a.ID,
                FullName = a.LastName + " " + a.FirstName
            }).ToListAsync();

            var model = new AddClincVM
            {
                UnassignedManagers = new SelectList(unassignedManagers, "ID", "FullName"),
            };

			var amTimes = new List<TimeOnly> {
				new TimeOnly(7, 0), new TimeOnly(7, 30), new TimeOnly(8, 0), new TimeOnly(8, 30),
				new TimeOnly(9, 0), new TimeOnly(9, 30), new TimeOnly(10, 0), new TimeOnly(10, 30),
				new TimeOnly(11, 0), new TimeOnly(11, 30), new TimeOnly(12, 0)
			};

			var pmTimes = new List<TimeOnly> {
				new TimeOnly(12, 0), new TimeOnly(12, 30), new TimeOnly(13, 0), new TimeOnly(13, 30),
				new TimeOnly(14, 0), new TimeOnly(14, 30), new TimeOnly(15, 0), new TimeOnly(15, 30),
				new TimeOnly(16, 0), new TimeOnly(16, 30), new TimeOnly(17, 0), new TimeOnly(17, 30),
				new TimeOnly(18, 0), new TimeOnly(18, 30), new TimeOnly(19, 0), new TimeOnly(19, 30),
				new TimeOnly(20, 0), new TimeOnly(20, 30), new TimeOnly(21, 0)
			};

			ViewBag.AmTimes = amTimes.Select(t => new SelectListItem
			{
				Value = t.ToString("HH:mm"),
				Text = t.ToString("HH:mm"),
				Selected = t.ToString("HH:mm") == model.AmStartTime || t.ToString("HH:mm") == model.AmEndTime
			}).ToList();

			ViewBag.PmTimes = pmTimes.Select(t => new SelectListItem
			{
				Value = t.ToString("HH:mm"),
				Text = t.ToString("HH:mm"),
				Selected = t.ToString("HH:mm") == model.PmStartTime || t.ToString("HH:mm") == model.PmEndTime
			}).ToList();

			return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> CreateClinic(AddClincVM model)
        {
            if (ModelState.IsValid)
            {
                //Kiểm tra Phòng khám đã tồn tại chưa
                bool clinicNameExists = await _context.Clinics.AnyAsync(c => c.Name == model.Name);
                if (clinicNameExists)
                {
                    ModelState.AddModelError("Name", "Tên phòng khám đã tồn tại.");
                }

                //Kiểm tra Hotline đã tồn tại chưa
                bool clinicPhoneExists = await _context.Clinics.AnyAsync(c => c.PhoneNumber == model.PhoneNumber);
                if (clinicPhoneExists)
                {
                    ModelState.AddModelError("PhoneNumber", "Số điện thoại đã tồn tại.");
                }

                //Kiểm tra Email phòng khám tồn tại chưa
                bool clinicEmailExists = await _context.Clinics.AnyAsync(c => c.Email == model.Email);
                if (clinicEmailExists)
                {
                    ModelState.AddModelError("Email", "Email đã tồn tại.");
                }

                //Nếu đã tồn tại, load lại danh sách
                if (!ModelState.IsValid)
                {
                    //List những quản lý chưa có phòng khám nào
                    var unassignedManager = await _context.Accounts
                        .Where(a => a.Role == "Quản Lý" && !_context.Clinics.Any(c => c.ManagerID == a.ID) && a.AccountStatus == "Hoạt Động")
                        .Select(a => new
                        {
                            a.ID,
                            FullName = a.LastName + " " + a.FirstName
                        })
                        .ToListAsync();

                    model.UnassignedManagers = new SelectList(unassignedManager, "ID", "FullName");

                    //Thời gian làm việc buổi sáng + chiều
					var amTime = new List<TimeOnly> {
				        new TimeOnly(7, 0), new TimeOnly(7, 30), new TimeOnly(8, 0), new TimeOnly(8, 30),
				        new TimeOnly(9, 0), new TimeOnly(9, 30), new TimeOnly(10, 0), new TimeOnly(10, 30),
				        new TimeOnly(11, 0), new TimeOnly(11, 30), new TimeOnly(12, 0)
			        };

					var pmTime = new List<TimeOnly> {
				        new TimeOnly(12, 0), new TimeOnly(12, 30), new TimeOnly(13, 0), new TimeOnly(13, 30),
				        new TimeOnly(14, 0), new TimeOnly(14, 30), new TimeOnly(15, 0), new TimeOnly(15, 30),
				        new TimeOnly(16, 0), new TimeOnly(16, 30), new TimeOnly(17, 0), new TimeOnly(17, 30),
				        new TimeOnly(18, 0), new TimeOnly(18, 30), new TimeOnly(19, 0), new TimeOnly(19, 30),
				        new TimeOnly(20, 0), new TimeOnly(20, 30), new TimeOnly(21, 0)
			        };

					ViewBag.AmTimes = amTime.Select(t => new SelectListItem
					{
						Value = t.ToString("HH:mm"),
						Text = t.ToString("HH:mm"),
						Selected = t.ToString("HH:mm") == model.AmStartTime || t.ToString("HH:mm") == model.AmEndTime
					}).ToList();

					ViewBag.PmTimes = pmTime.Select(t => new SelectListItem
					{
						Value = t.ToString("HH:mm"),
						Text = t.ToString("HH:mm"),
						Selected = t.ToString("HH:mm") == model.PmStartTime || t.ToString("HH:mm") == model.PmEndTime
					}).ToList();

					return View(model);
                }


                //Kiểm tra Account Quản lý có tồn tại không, và đúng Role Quản lý chưa
                var manager = await _context.Accounts
                    .FirstOrDefaultAsync(a => a.ID == model.ManagerID && a.Role == "Quản Lý");

                if (manager == null)
                {
                    ModelState.AddModelError(string.Empty, "Không tìm thấy Role là Quản Lý.");
                    return View(model);
                }

				var clinic = new Clinic
				{
					Name = model.Name,
					PhoneNumber = model.PhoneNumber,
					Email = model.Email,
					ManagerID = manager.ID,
					Province = model.Province,
					District = model.District,
					Ward = model.Ward,
					ProvinceName = model.ProvinceName,
					DistrictName = model.DistrictName,
					WardName = model.WardName,
					Address = model.Address,
					Description = model.Description,
					Image = model.Image,
					ClinicStatus = "Hoạt Động"
				};

				//Check thời gian làm việc có tồn tại không?
				//Nếu không, thêm vào
				TimeOnly amStart = TimeOnly.Parse(model.AmStartTime);
				TimeOnly amEnd = TimeOnly.Parse(model.AmEndTime);
				TimeOnly pmStart = TimeOnly.Parse(model.PmStartTime);
				TimeOnly pmEnd = TimeOnly.Parse(model.PmEndTime);

				var amWorkTime = await _context.WorkTimes

Dental_Clinic_System/Dental_Clinic_System/Areas/Admin/Views/ManagerClinic/ApprovalRequest.cshtml
@model Dental_Clinic_System.Areas.Admin.ViewModels.BusinessPartnershipViewModel
@{
    ViewData["Title"] = "Đơn Hợp Tác";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" href="~/assets/fonts/stylesheet.css" />

<style>
    .modal-content {
        font-family: "Baloo Paaji 2" !important;
        font-size: 2rem;
    }

    .modal-body input {
        font-family: "Baloo Paaji 2" !important;
        font-size: 2rem;
    }

    .modal-body textarea {
        font-family: "Baloo Paaji 2" !important;
        font-size: 2rem;
    }

    .modal-body p {
        font-family: "Baloo Paaji 2" !important;
        font-size: 2rem;
        font-weight: 600;
    }

    .sidebar .nav-item a.Approval {
        color: #fff;
        background: #4880ff;
    }
</style>

<div class="account__management__header">
    <div class="title">Thông Tin Hợp Tác Kinh Doanh</div>
    <div class="action-btn">
        <!-- TÌM KIẾM -->
        @* <form action="~/Admin/Account/SearchLockedAccount" method="get">
        <input type="hidden" name="role" />
        <div class="search__bar">
        <input type="search" placeholder="Tìm kiếm ..." name="keyword" />
        </div>
        </form> *@

    </div>
</div>

<table class="table table-striped mt-5" style="font-size: 1.6rem">
    <thead>
        <tr>
            <th class="text-center">STT</th>
            <th>Tên Doanh Nghiệp</th>
            <th>Số Điện Thoại</th>
            <th>Địa Chỉ Email</th>
            <th>Tên Người Đại Diện</th>
            <th>Tên Phòng Khám</th>
            @* <th>Địa Chỉ Phòng Khám</th> *@
            <th>Tên Miền</th>
            <th>Nội Dung</th>
            <th class="text-center">Hành Động</th>
        </tr>
    </thead>
    <tbody id="myTableBody">
        @if (Model.BusinessPartnerships != null)
        {
            int count = 1;

            @foreach (var order in Model.BusinessPartnerships)
            {
                @if (order.Status == "Chưa Duyệt")
                {
                    <tr style="vertical-align: middle">
                        <td class="text-center">@count</td>
                        <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">@order.CompanyName</td>
                        <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">@order.CompanyPhonenumber</td>
                        <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">@order.CompanyEmail</td>
                        <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">@order.RepresentativeName</td>
                        <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">@order.ClinicName</td>
                        @* <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">@order.ClinicAddress</td> *@
                        <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">
                            @if (!string.IsNullOrEmpty(order.DomainName))
                            {
                                <a href="@order.DomainName" target="_blank">@order.DomainName</a>
                            }
                        </td>
                        <td style="word-wrap: break-word; max-width: 300px; padding: 10px;">
                            <div class="content-preview">
                                @(order.Content.Length > 50 ? order.Content.Substring(0, 50) : order.Content)
                                @if (order.Content.Length > 50)
                                {
                                    <a href="javascript:void(0);" onclick="showFullContent(this);" data-full-content="@order.Content" data-short-content="@order.Content.Substring(0, 50)">Xem Thêm</a>
                                }
                            </div>
                        </td>
                        <td style="text-align: center;">
                            <form style="display: inline;">
                                <button type="button" class="btn btn-view btn-icon" onclick="viewApprovalRequest(@order.ID)">
                                    <i class="fa-solid fa-eye"></i>
                                </button>
                            </form>

                            <form action="@Url.Action("ProcessRequest", "ManagerClinic", new {area = "Admin"})" method="post" style="display: inline;">
                                <input type="hidden" name="orderId" value="@order.ID" />
                                <input type="hidden" name="orderStatus" value="Đồng Ý" />
                                <button type="submit" class="btn btn-success" style="font-size: 1.4rem; padding: 10px 30px; width: 120px;">
                                    <i class="fa-solid fa-check"></i>
                                </button>
                            </form>
                            <form action="@Url.Action("ProcessRequest", "ManagerClinic", new {area = "Admin"})" method="post" style="display: inline;">
                                <input type="hidden" name="orderId" value="@order.ID" />
                                <input type="hidden" name="orderStatus" value="Từ Chối" />
                                <button type="submit" class="btn btn-danger" style="font-size: 1.4rem; padding: 10px 30px; width: 120px;">
                                    <i class="fa-solid fa-xmark"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    count++;
                }
            }
        }
    </tbody>
</table>

<!-- Requet Modal-->
<div class="modal fade" id="viewApprovalRequestModal" tabindex="-1" aria-labelledby="viewApprovalRequestModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" style="max-width: 50% !important">
        <div class="modal-content">
            <div class="modal-header" style="flex-direction: column-reverse;">
                <h1 class="modal-title" id="viewApprovalRequestModalLabel">Chi tiết đơn duyệt</h1>
                @* <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> *@
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="mb-3 col-md-6">
                        <p class="form-label">Tên doanh nghiệp</p>
                        <input type="text" id="viewCompanyName" class="form-control" readonly />
                    </div>
                    
                    <div class="mb-3 col-md-6">
                        <p class="form-label">Tên người đại diện</p>
                        <input type="text" id="viewRepresentativeName" class="form-control" readonly />
                    </div>
                </div>

                <div class="row">
                    <div class="mb-3 col-md-6">
                        <p class="form-label">Số điện thoại liên hệ</p>
                        <input type="number" id="viewManagerPhoneNumber" class="form-control" readonly />
                    </div>

                    <div class="mb-3 col-md-6">
                        <p class="form-label">Địa chỉ Email người đại diện</p>
                        <input type="email" id="viewManagerEmail" class="form-control" value="" readonly />
                    </div>
                </div>

                <div class="row">
                    <div class="mb-3 col-md-6">
                        <p class="form-label">Tên phòng khám</p>
                        <input type="text" id="viewClinicName" class="form-control" readonly />
                    </div>

                    <div class="mb-3 col-md-6">
                        <p class="form-label">Địa chỉ phòng khám</p>
                        <input type="text" id="viewClinicAddress" class="form-control" readonly />
                    </div>
                </div>

                <div class="row">
                    <div class="mb-3 col-md-6">
                        <p class="form-label">Hotline (Đường dây nóng)</p>
                        <input type="number" id="viewCompanyPhoneNumber" class="form-control" readonly />
                    </div>

                    <div class="mb-3 col-md-6">
                        <p class="form-label">Địa chỉ Email Doanh Nghiệp</p>
                        <input type="email" id="viewCompanyEmail" class="form-control" value="" readonly />
                    </div>
                </div>

                <div class="row">
                    <div class="mb-3 col-md-12">
                        <p class="form-label">Tên miền</p>
                        <a href="" id="viewDomainName" class="form-control">
                            <p id="textDomainName"></p>
                        </a>

                    </div>
                </div>

                @* <div class="row">
                <div class="mb-3 col-md-4">
                <p class="form-label">Tỉnh / Thành phố</p>
                <input type="text" id="viewProvinceName" class="form-control" readonly />
                </div>

                <div class="mb-3 col-md-4">
                <p class="form-label">Quận / Huyện</p>
                <input type="text" id="viewDistrictName" class="form-control" readonly />
                </div>

                <div class="mb-3 col-md-4">
                <p class="form-label">Phường / Xã</p>
                <input type="text" id="viewWardName" class="form-control" readonly />
                </div>
                </div> *@

                <div class="row">
                    <div class="mb-3 col-md-6">
                        <p class="form-label">Thời gian làm việc buổi sáng</p>
                        <input type="text" id="viewAmWorkTime" class="form-control" readonly />
                    </div>

                    <div class="mb-3 col-md-6">
                        <p class="form-label">Thời gian làm việc buổi chiều</p>
                        <input type="text" id="viewPmWorkTime" class="form-control" readonly />
                    </div>
                </div>

                <div class="row">
                    <div class="mb-3 col-md-12">
                        <div class="text-center">
                            <p class="form-label">Logo phòng khám</p>
                            <img id="viewImage" src="" alt="Clinic Image" style="max-width: 50%; border-radius: 10px;" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="mb-3 col-md-12">
                        <p class="form-label">Nội dung</p>
                        <textarea type="text" id="viewContent" class="form-control" rows="10" readonly></textarea>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="font-size: 2rem; background-color: #dc3545; border-color: #dc3545;">Đóng</button>
            </div>
        </div>
    </div>
</div>

<script>
    function viewApprovalRequest(id) {
        $.ajax({
            url: '@Url.Action("ViewApprovalRequest", "ManagerClinic")',
            type: 'POST',
            data: { id: id },
            success: function (data) {
                $('#viewCompanyName').val(data.companyName);
                $('#viewCompanyEmail').val(data.companyEmail);
                $('#viewCompanyPhoneNumber').val(data.companyPhonenumber);
                $('#viewManagerEmail').val(data.managerEmail);
                $('#viewManagerPhoneNumber').val(data.managerPhonenumber);
                $('#viewRepresentativeName').val(data.representativeName);
                $('#viewClinicName').val(data.clinicName);
                $('#viewClinicAddress').val(data.clinicAddress);
                $('#textDomainName').text(data.domainName);
                $('#viewContent').val(data.content);
                $('#viewProvinceName').val(data.provinceName);
                $('#viewDistrictName').val(data.districtName);
                $('#viewWardName').val(data.wardName);
                $('#viewAmWorkTime').val(data.amWorkTime);
                $('#viewPmWorkTime').val(data.pmWorkTime);

                $('#viewDomainName').attr('href', data.domainName);
                $('#viewImage').attr('src', data.image);
                $('#viewApprovalRequestModal').modal('show');
            }
        });
    }
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
    function showFullContent(element) {
        var isExpanded = element.getAttribute('data-expanded') === 'true';
        var fullContent = element.getAttribute('data-full-content');
        var shortContent = element.getAttribute('data-short-content');

        if (isExpanded) {
            element.parentElement.innerHTML = shortContent + ' <a href="javascript:void(0);" onclick="showFullContent(this);" data-full-content="' + fullContent + '" data-short-content="' + shortContent + '" data-expanded="false">Xem Thêm</a>';
        } else {
            element.parentElement.innerHTML = fullContent + ' <a href="javascript:void(0);" onclick="showFullContent(this);" data-full-content="' + fullContent + '" data-short-content="' + shortContent + '" data-expanded="true">Thu Gọn</a>';
        }
    }

    // function approveOrder(orderId) {
    //     // Logic to approve order
    //     alert('Order ' + orderId + ' approved.');
    // }

    // function rejectOrder(orderId) {
    //     // Logic to reject order
    //     alert('Order ' + orderId + ' rejected.');
    // }
</script>

Dental_Clinic_System/Dental_Clinic_System/Areas/Admin/Views/ManagerClinic/ListClinicClosed.cshtml
@model IEnumerable<Dental_Clinic_System.Areas.Admin.ViewModels.ManagerClinicVM>

@{
	ViewData["Title"] = "Danh sách phòng khám đã đóng cửa";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- TÌM KIẾM (SEARCH)-->
<!-- Clinic management header -->
<div class="clinic__management__header">
	<h1 class="title">Phòng khám đã đóng cửa</h1>
	<div class="action-btn">
		<form action="~/Admin/ManagerClinic/ListClinicClosed" method="get">
			<div class="search__bar">
				<input type="search" placeholder="Tìm kiếm ..." name="search" />
			</div>
		</form>
	</div>
</div>

<!--VIEW-->
<div class="modal fade" id="clinicDetailsModal" tabindex="-1" role="dialog" aria-labelledby="clinicDetailsModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="clinicDetailsModalLabel">Chi tiết phòng khám</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="image-column">
						<img id="clinicImage" class="img-fluid" alt="Clinic Image">

					</div>
					<div class="form-column">
						<form>
							<div class="form-row">
								<div class="form-group col-md-6">
									<label for="clinicName">Tên phòng khám</label>
									<input type="text" class="form-control1" id="clinicName" readonly>
								</div>
								<div class="form-group col-md-6">
									<label for="clinicManagerName">Quản lý</label>
									<input type="text" class="form-control1" id="clinicManagerName" readonly>
								</div>
							</div>
							<div class="form-row">

								<div class="form-group col-md-6">
									<label for="clinicEmail">Email của phòng khám</label>
									<input type="text" class="form-control1" id="clinicEmail" readonly>
								</div>
								<div class="form-group col-md-6">
									<label for="clinicPhoneNumber">Hotline</label>
									<input type="text" class="form-control1" id="clinicPhoneNumber" readonly>
								</div>
							</div>
							<div class="form-group">
								<label for="clinicAddress">Địa chỉ</label>
								<input type="text" class="form-control1" id="clinicAddress" readonly>
							</div>
							<div class="form-row">
								<div class="form-group col-md-4">
									<label for="clinicProvince">Tỉnh/Thành phố</label>
									<input type="text" class="form-control1" id="clinicProvince" readonly>
								</div>
								<div class="form-group col-md-4">
									<label for="clinicDistrict">Quận/Huyện</label>
									<input type="text" class="form-control1" id="clinicDistrict" readonly>
								</div>
								<div class="form-group col-md-4">
									<label for="clinicWard">Phường/Xã</label>
									<input type="text" class="form-control1" id="clinicWard" readonly>
								</div>
							</div>
							<div class="form-group">
								<label for="clinicDescription">Mô tả</label>
								<textarea class="form-control1" id="clinicDescription" rows="3" readonly></textarea>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="close-btn btn" data-bs-dismiss="modal">
					Đóng
				</button>
			</div>
		</div>
	</div>
</div>


<!--SHOW LIST-->
<!-- CLINIC LIST MANAGEMENT -->
<div id="myItem" class="clinic__management__wrapper row">
	@foreach (var clinic in Model)
	{
		<div class="clinic-wrap-item col-md-6">
			<div class="clinic-wrap-item__style row">
				<div class="img-content col-md-6">
					<img src="@clinic.Image" alt="Clinic" />
				</div>
				<div class="info-content col-md-6">
					<h2 class="title-Name-Clinic">@clinic.ClinicName</h2>
					<div class="name">Quản lý: <span class="title-Address">@clinic.ManagerName</span></div>
					<div class="address"> Địa chỉ: <span class="tittle-Address">@clinic.ProvinceName</span> </div>
					<div class="action">
						<a href="tel:0123456789"><i class="fa-solid fa-phone-volume"></i></a>
						<a href="mailto:example@gmail.com"><i class="fa-solid fa-envelope"></i></a>

						<!--VIEW BUTTON-->
						<button type="button" class="btn btn-view btn-icon" onclick="viewClinicClosed(@clinic.Id)">
							<i class="fa-solid fa-eye"></i>
						</button>

						<!--UNLOCK-->
						<form action="~/Admin/ManagerClinic/UnlockClinic" method="post" onsubmit="return confirm('Bạn có chắc chắn muốn mở lại phòng khám này không?');">
							<input type="hidden" name="name" value="@clinic.ClinicName" />
							<input type="hidden" name="status" value="Hoạt Động" />
							<button class="unlock">
								<i class="fa-solid fa-unlock" style="color:white"></i>
							</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	}
</div>

<!-- ========== PAGINATION  ========== -->
<ul class="pagination" id="pagination">
</ul>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

@* Chỉnh sửa UI *@
<link rel="stylesheet" href="~/assets/css/clinicClosed.css" />

@section Scripts {
	<script>
		function viewClinicClosed(clinicId) {
			// Sử dụng AJAX để lấy thông tin chi tiết về phòng khám
			$.ajax({
				url: '@Url.Action("ViewClinic", "ManagerClinic", new { Area = "Admin" })',
				type: 'GET',
				data: { id: clinicId },
				success: function (data) {
					// Điền vào các fields với dữ liệu
					$('#clinicName').val(data.name);
					$('#clinicPhoneNumber').val(data.phoneNumber);
					$('#clinicEmail').val(data.email);
					$('#clinicManagerName').val(data.managerName);
					$('#clinicProvince').val(data.provinceName);
					$('#clinicDistrict').val(data.districtName);
					$('#clinicWard').val(data.wardName);
					$('#clinicAddress').val(data.address);
					$('#clinicDescription').val(data.description);
					$('#clinicImage').attr('src', data.image);
					$('#clinicStatus').val(data.clinicStatus);

					// Hiển thị modal
					$('#clinicDetailsModal').modal('show');
				}
			});
		}
	</script>

}