Dental_Clinic_System/Dental_Clinic_System/Areas/Admin/Controllers/AccountDentistController.cs
//==============================================TÀI KHOẢN NHA SĨ================================================
using Dental_Clinic_System.Areas.Admin.ViewModels;
using Dental_Clinic_System.Helper;
using Dental_Clinic_System.Models.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace Dental_Clinic_System.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "GetAppointmentStatus", Roles = "Admin, Mini Admin")]

    public class AccountDentistController : Controller
    {
        private readonly DentalClinicDbContext _context;

        public AccountDentistController(DentalClinicDbContext context)
        {
            _context = context;
        }

        #region Show List Account với Role Nha Sĩ
        //===================LIST ACCOUNT===================
        //[Route("ListAccountDentist")]
        public async Task<IActionResult> ListAccountDentist()
        {
            var accounts = await _context.Accounts
            .Where(a => a.AccountStatus == "Hoạt Động" && a.Role == "Nha Sĩ")
            .ToListAsync();

            var accountList = accounts.Select(a => new ManagerAccountVM
            {

                Id = a.ID,
                Username = a.Username,
                Email = a.Email,
                FirstName = a.FirstName,
                LastName = a.LastName,
                PhoneNumber = a.PhoneNumber,
                Address = a.Address,
                Gender = a.Gender,
                //Role = a.Role,

                ClinicName = _context.Dentists
                    .Where(d => d.AccountID == a.ID)
                    .Select(d => d.Clinic.Name)
                    .FirstOrDefault(),

                Specialties = _context.DentistSpecialties
                    .Where(ds => ds.Dentist.AccountID == a.ID && ds.Check == true)
                    .Select(ds => ds.Specialty.Name)
                    .ToList()
            }).ToList();


            return View(accountList);
        }
        #endregion

        #region Tìm kiếm (Search)
        //===================TÌM KIẾM===================
        //[Route("SearchAccount")]
        public async Task<IActionResult> SearchAccount(string keyword)
        {
            //Nếu keyword rỗng, sẽ chuyển hướng đến ListAccount
            if (string.IsNullOrEmpty(keyword))
            {
                return RedirectToAction(nameof(ListAccountDentist));
            }

            var accountQuesry = _context.Accounts
            .Where(a => a.Username.Contains(keyword) && a.AccountStatus == "Hoạt Động" && a.Role == "Nha Sĩ");

            var account = await accountQuesry.Where(a => a.Username.Contains(keyword)).ToListAsync();

            var accountList = account.Select(a => new ManagerAccountVM
            {
                Id = a.ID,
                Username = a.Username,
                FirstName = a.FirstName,
                LastName = a.LastName,
                Email = a.Email,
                PhoneNumber = a.PhoneNumber,
                Address = a.Address,
                Gender = a.Gender,
                //Role = a.Role,

                ClinicName = _context.Dentists
                    .Where(d => d.AccountID == a.ID)
                    .Select(d => d.Clinic.Name)
                    .FirstOrDefault(),

                Specialties = _context.DentistSpecialties
                    .Where(ds => ds.Dentist.AccountID == a.ID && ds.Check == true)
                    .Select(ds => ds.Specialty.Name)
                    .ToList()
                
            }).ToList();

            return View("ListAccountDentist", accountList);
        }
        #endregion

        #region Thêm tài khoản (Add Account)
        [HttpGet]
        public async Task<IActionResult> GetDegrees()
        {
            var degrees = await _context.Degrees.ToListAsync();
            return Json(degrees);
        }

        [HttpGet]
        public async Task<IActionResult> GetClinics()
        {
            var clinic = await _context.Clinics.ToListAsync();
            return Json(clinic);
        }

        [HttpGet]
        public async Task<IActionResult> GetSpecialties()
        {
            var specialties = await _context.Specialties.ToListAsync();
            return Json(specialties);
        }

        //===================THÊM TÀI KHOẢN===================
        [HttpPost]
        public async Task<IActionResult> AddAccount(string username, string password, string phoneNumber, string email, string gender, string firstname, string lastname, int degreeID, int clinicID, List<int> selectSpecialty)
        {
            //Check thông tin trùng lặp
            var existingAccount = await _context.Accounts
                .FirstOrDefaultAsync(a => a.Email == email || a.PhoneNumber == phoneNumber || a.Username == username);

            if (existingAccount != null)
            {
                //Kiểm tra tên đăng nhập đã tồn tại chưa
                bool accountName = await _context.Accounts.AnyAsync(a => a.Username == username);
                if (accountName)
                {
                    ModelState.AddModelError("Name", "Tên đăng nhập đã tồn tại");
                }

                //Kiểm tra sđt đã tồn tại chưa
                bool accountPhoneNumber = await _context.Accounts.AnyAsync(a => a.PhoneNumber == phoneNumber);
                if (accountPhoneNumber)
                {
                    ModelState.AddModelError("PhoneNumber", "Số điện thoại đã tồn tại");
                }

                //Kiểm tra Email đã tồn tại chưa
                bool accountEmail = await _context.Accounts.AnyAsync(a => a.Email == email);
                if (accountEmail)
                {
                    ModelState.AddModelError("Email", "Email đã tồn tại");
                }

                //Lấy lại list account để hiển thị
                var account1 = await _context.Accounts
                    .Where(a => a.AccountStatus == "Hoạt Động" && a.Role == "Nha Sĩ")
                    .ToListAsync();

                var accountList = account1.Select(a => new ManagerAccountVM
                {
					Id = a.ID,
					FirstName = a.FirstName,
					LastName = a.LastName,
					Username = a.Username,
					Email = a.Email,
					PhoneNumber = a.PhoneNumber,
					Address = a.Address,
					Gender = a.Gender,
					//Role = a.Role,

					ClinicName = _context.Dentists
					.Where(d => d.AccountID == a.ID)
					.Select(d => d.Clinic.Name)
					.FirstOrDefault(),

					Specialties = _context.DentistSpecialties
					.Where(ds => ds.Dentist.AccountID == a.ID && ds.Check == true)
					.Select(ds => ds.Specialty.Name)
					.ToList()
				}).ToList();

                return View("ListAccountDentist", accountList);
            }

            //Thêm mới Account vào DB
            var account = new Account
            {
                Username = username,
                FirstName = firstname,
                LastName = lastname,
                Password = DataEncryptionExtensions.ToMd5Hash(password),
                PhoneNumber = phoneNumber,
                Email = email,
                Gender = gender,
                Role = "Nha Sĩ",
                AccountStatus = "Hoạt Động"
            };
            _context.Accounts.Add(account);
            await _context.SaveChangesAsync();

            //Thêm mới Dentist vào DB
            var newDentist = new Dental_Clinic_System.Models.Data.Dentist
            {
                AccountID = account.ID,
                ClinicID = clinicID,
                DegreeID = degreeID,
            };
            _context.Dentists.Add(newDentist);
            await _context.SaveChangesAsync();

            //Thêm mới Dentist có nhiều Specialty (Chuyên khoa)
            var specialties = await _context.Specialties.ToListAsync();
            foreach (var s in specialties)
            {
                var dentistSpecialty = new DentistSpecialty
                {
                    DentistID = newDentist.ID,
                    SpecialtyID = s.ID,
                    Check = selectSpecialty.Contains(s.ID)
                };
                _context.DentistSpecialties.AddAsync(dentistSpecialty);
            }
            await _context.SaveChangesAsync();

            var dentists = await _context.Dentists
                .Include(d => d.Account)
                .Include(d => d.Clinic)
                .Include(d => d.Degree)
                .ToListAsync();

            TempData["ToastMessageSuccessTempData"] = "Đăng ký tài khoản nha sĩ thành công";
            return RedirectToAction(nameof(ListAccountDentist), dentists);
        }
        #endregion

        #region Chỉnh sửa (Edit Account)
        //===================CHỈNH SỬA TÀI KHOẢN===================
        [HttpGet]
        public async Task<IActionResult> EditAccountDentist(int id)
        {
            var account = await _context.Accounts.FindAsync(id);
            if (account == null)
            {
                Console.WriteLine($"Account với ID {id} không tìm thấy.");
                return NotFound();
            }

            var dentist = await _context.Dentists.FirstOrDefaultAsync(d => d.AccountID == id);
            if (dentist == null)
            {
                Console.WriteLine($"Dentist với AccountID {id} không tìm thấy.");
                return NotFound();
            }

            var selectSpecialty = await _context.DentistSpecialties
                .Where(ds => ds.DentistID == dentist.ID && ds.Check == true)
                .Select(ds => ds.SpecialtyID)
                .ToListAsync();

            var accountVM = new EditAccountDentistVM
            {
                Id = account.ID,
                FirstName = account.FirstName,
                LastName = account.LastName,
                Username = account.Username,
                Email = account.Email,

Dental_Clinic_System/Dental_Clinic_System/Areas/Admin/Views/AccountDentist/ListAccountDentist.cshtml
@model IEnumerable<Dental_Clinic_System.Areas.Admin.ViewModels.ManagerAccountVM>

@{
	ViewData["Title"] = "Danh sách tài khoản nha sĩ";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
	.inline-block {
		display: inline-block;
		vertical-align: top;
	}

	.form-inline {
		display: inline-block;
		margin: 0;
	}

	.account__management .color-trash button {
		background: rgb(255, 66, 66); /* Nền đỏ */
		color: white; /* Màu chữ trắng */
	}

	.sidebar .nav-item a.Quan_ly_tai_khoan {
		color: #fff;
		background: #4880ff;
	}

	.modal-content {
		--mdb-modal-box-shadow: 0 6px 45px -9px rgba(var(--mdb-box-shadow-color-rgb), 0.21), 0 30px 60px -6px rgba(var(--mdb-box-shadow-color-rgb), 0.12);
		border: 0;
		box-shadow: var(--mdb-modal-box-shadow);
		padding: 1px 8px !important;
		border-radius: 17px;
	}

	.form-modal-styles {
		width: 46%;
	}

	.specialties-container {
		display: flex;
		flex-wrap: wrap;
		gap: 10px;
	}

	.form-check {
		width: calc(50% - 10px);
		align-items: center;
	}

	.form-check-label {
		margin-left: -27px;
	}

	.account__management .table tbody span {
		font-weight: 200;
	}

	#specialties .form-check-input {
		margin-right: 10px;
		width: auto;
	}

	#specialties .form-check-label {
		margin-left: 3px;
		font-size: 1.7rem;
	}
</style>


<!-- TÌM KIẾM (SEARCH)-->
<!-- account management header -->
<div class="account__management__header">
	<div class="title">Tài khoản nha sĩ</div>
	<div class="action-btn">
		<form action="~/Admin/AccountDentist/SearchAccount" method="get">
			<div class="search__bar">
				<input type="search" placeholder="Tìm kiếm ..." name="keyword" />
			</div>
		</form>

		<button type="button"
				data-bs-toggle="modal"
				data-bs-target="#myModal"
				class="add__new">
			+ Thêm
		</button>
	</div>
</div>


<!-- Modal For Add new User -->
<!-- THÊM MỚI NGƯỜI DÙNG (ADD)-->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="mainTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered form-modal-styles">
		<form action="~/Admin/AccountDentist/AddAccount" method="POST" class="modal-content" onsubmit="return validateForm()">
			<div class="modal-header">
				<h1 class="modal-title fs-10" id="mainTitle">
					Thêm mới tài khoản nha sĩ
				</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="row mb-3">
					<div class="col">
						<label for="username">Tên đăng nhập<sup style="color:red">*</sup></label>
						<input type="text" name="Username" id="username" required />
						<span id="usernameError" class="text-danger"></span>
						<span for="Name" class="text-danger"></span>
					</div>
					<div class="col">
						<label for="password">Mật khẩu<sup style="color:red">*</sup></label>
						<input type="password" name="Password" id="password" required />
						<span id="passwordError" class="text-danger"></span>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col-12 col-md-6">
						<label for="lastname">Họ<sup style="color:red">*</sup></label>
						<input type="text" id="lastame" name="LastName" required />
					</div>
					<div class="col-12 col-md-4">
						<label for="firstname">Tên<sup style="color:red">*</sup></label>
						<input type="text" id="firstname" name="FirstName" required />
					</div>
					<div class="col-12 col-md-2">
						<label for="gender">Giới tính</label>
						<select id="gender" name="Gender" class="form-control">
							<option value="Nam">Nam</option>
							<option value="Nữ">Nữ</option>
						</select>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col">
						<label for="email">Email<sup style="color:red">*</sup></label>
						<input type="email" name="Email" id="email" required />
						<span id="emailError" class="text-danger"></span>
						<span for="Email" class="text_danger"></span>
					</div>
					<div class="col">
						<label for="phonenumber">Số điện thoại<sup style="color:red">*</sup></label>
						<input type="tel" name="PhoneNumber" id="phonenumber" required />
						<span id="phoneNumberError" class="text-danger"></span>
						<span for="PhoneNumber" class="text_danger"></span>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col">
						<label for="degreeID">Học vị<sup style="color:red">*</sup></label>
						<select name="DegreeID" id="degreeID" class="form-control" required></select>
					</div>
					<div class="col">
						<label for="clinicID">Phòng khám<sup style="color:red">*</sup></label>
						<select name="ClinicID" id="clinicID" class="form-control" required></select>
					</div>
				</div>
				<div class="row mb-3">
					<div class="col">
						<label for="specialties">Các chuyên khoa gồm có:<sup style="color:red">*</sup></label>
						<div id="specialties" class="specialties-container"></div>
					</div>
				</div>

			</div>

			<div class="modal-footer">
				<button type="button" class="close-btn btn" data-bs-dismiss="modal">
					Đóng
				</button>
				<button type="submit" class="submit-btn btn">
					Lưu
				</button>
			</div>
		</form>
	</div>
</div>


<!-- Thông báo lỗi bị trùng -->
@if (!ViewData.ModelState.IsValid)
{
	<div class="alert alert-danger" role="alert">
		@foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
		{
			<span>@error.ErrorMessage</span>

			<br />
		}
	</div>
}

<!--SHOW LIST-->
<table class="table table-striped mt-5" style="font-size: 1.6rem">
	<thead>
		<tr>
			<th class="text-center">STT</th>
			<th>Tên đăng nhập</th>
			<th>Họ tên</th>
			<th>Giới tính</th>
			<th>Phòng khám</th>
			<th>Chuyên khoa</th>
			<th>Email</th>
			<th>Số điện thoại</th>
			<th>Hành động</th>
		</tr>
	</thead>
	<tbody id="myTableBody">
		@if (Model != null && Model.Any())
		{
			int stt = 1;
			@foreach (var account in Model)
			{
				<tr style="vertical-align: middle">
					<td style="text-align: center">@stt</td>
					<td>
						@* <img src="~/assets/images/avatar.jpg" alt="" /> *@
						@account.Username
					</td>
					<td>@account.LastName @account.FirstName</td>
					<td>@account.Gender</td>
					<td>@account.ClinicName</td>
					<td>
						@foreach (var specialty in account.Specialties)
						{
							<span class="specialty-item">@specialty</span> <br />
						}
					</td>
					<td>@account.Email</td>
					<td>@account.PhoneNumber</td>
					<td>
						<!--EDIT-->
						<a asp-area="Admin" asp-controller="AccountDentist" asp-action="EditAccountDentist" asp-route-id="@account.Id" class="inline-block">
							<button type="button">
								<i class="bx bxs-edit"></i>
							</button>
						</a>

						<!--DELETE-->
						<form action="~/Admin/AccountDentist/HiddenAccountStatus" method="post" class="form-inline" onsubmit="return confirm('Bạn có chắc chắn muốn khóa tài khoản này không?');">
							<input type="hidden" name="username" value="@account.Username" />
							<input type="hidden" name="status" value="Bị Khóa" />
							<a href="#!" class="color-trash">
								<button type="submit">
									<i class="bx bxs-lock"></i>
								</button>
							</a>
						</form>
					</td>
				</tr>
				stt++;
			}
		}
	</tbody>
</table>

<!-- ========== PAGINATION  ========== -->
<ul class="pagination" id="pagination">
</ul>

<script src="~/assets/js/pagination.js"></script>


@section Scripts {
	<!-- Thông báo lỗi -->
	<script>
		function validateForm() {
			let isValid = true;

			//Xác thực Username
			const username = document.getElementById('username').value;
			const usernameError = document.getElementById('usernameError');
			const usernameRegex = /^[a-zA-Z][a-zA-Z0-9]{2,29}$/;
			if (!usernameRegex.test(username)) {
				usernameError.innerText = "Tên đăng nhập phải có ít nhất 3 ký tự, chỉ chứa các chữ cái và số, và bắt đầu bằng chữ cái.";
				isValid = false;
			} else {
				usernameError.innerText = "";
			}

			//Xác thực mật khẩu
			const password = document.getElementById('password').value;
			const passwordError = document.getElementById('passwordError');
			const passwordRegex = /^[a-zA-Z][a-zA-Z0-9]{2,29}$/;
			if (!passwordRegex.test(password)) {
				passwordError.innerText = "Mật khẩu phải có ít nhất 3 ký tự, chỉ chứa các chữ cái và số, và bắt đầu bằng chữ cái.";
				isValid = false;
			} else {
				passwordError.innerText = "";
			}

			//Xác thực Email
			const email = document.getElementById('email').value;
			const emailError = document.getElementById('emailError');
			if (email.length < 3 || email.length > 50) {
				emailError.innerText = "Email phải có ít nhất 3 ký tự và không vượt quá 50 ký tự.";
				isValid = false;
			} else {
				emailError.innerText = "";
			}

			//Xác thực số điện thoại
			const phoneNumber = document.getElementById('phonenumber').value;
			const phoneNumberError = document.getElementById('phoneNumberError');
			const phoneNumberRegex = /^\d{9,11}$/;
			if (!phoneNumberRegex.test(phoneNumber)) {
				phoneNumberError.innerText = "Số điện thoại phải có độ dài từ 9 đến 11 số.";
				isValid = false;
			} else {
				phoneNumberError.innerText = "";
			}

			return isValid;
		}
	</script>

	<!--  -->
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
		$(document).ready(function () {
			$('#myModal').on('show.bs.modal', function (e) {
				var degreesRequest = $.ajax({
					url: '@Url.Action("GetDegrees", "AccountDentist")',
					type: 'GET'
				});

				var clinicsRequest = $.ajax({
					url: '@Url.Action("GetClinics", "AccountDentist")',
					type: 'GET'
				});

				var specialtiesRequest = $.ajax({
					url: '@Url.Action("GetSpecialties", "AccountDentist")',
					type: 'GET'
				});

				$.when(degreesRequest, clinicsRequest, specialtiesRequest).done(function (degreesResponse, clinicsResponse, specialtiesResponse) {
					var degreesData = degreesResponse[0];
					var clinicsData = clinicsResponse[0];
					var specialtiesData = specialtiesResponse[0];

					var degreeSelect = $('#degreeID');
					degreeSelect.empty();
					degreesData.forEach(function (degree) {
						degreeSelect.append(new Option(degree.name, degree.id));
					});

					var clinicSelect = $('#clinicID');
					clinicSelect.empty();
					clinicsData.forEach(function (clinic) {
						clinicSelect.append(new Option(clinic.name, clinic.id));
					});

					// var specialtySelect = $('#specialtyID');
					// specialtySelect.empty();
					// specialtiesData.forEach(function (specialty) {
					// 	specialtySelect.append(new Option(specialty.name, specialty.id));
					// });
					var specialtyDiv = $('#specialties');
					specialtyDiv.empty();
					specialtiesData.forEach(function (specialty) {
						specialtyDiv.append('<div class="form-check">' +
							'<label class="form-check-label" for="specialty' + specialty.id + '">' + specialty.name + '</label>' +
							'<input class="form-check-input" type="checkbox" value="' + specialty.id + '" id="specialty' + specialty.id + '" name="selectSpecialty">' +
							'</div>');
					});
				}).fail(function () {
					alert('Không truy cập được bằng cấp, phòng khám hoặc chuyên khoa.');
				});
			});
		});
	</script>
}